name: Swift

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  macOS:
    name: Build on macOS
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift -version
      - name: Build
        run: swift build -v

  linux:
    name: Build on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
      - uses: actions/checkout@v1
      - name: Swift Version
        run: swift -version
      - name: Build
        run: swift build
